### PR TITLE
Update backend calls to match changes to the CDS API

### LINKED ISSUE #68: Soil moisture requests failing due to CDS API changes
The CDS server has recently changed the API for the soil moisture dataset: the valid version specifiers are no longer

```text
'v201706.0.0', 'v201812.0.0', 'v201812.0.1', 'v201912.0.0'
```

but

```text
'v201706', 'v201812', 'v201912', 'v202012',
```

This results in an error when an old-style version specifier is supplied (or when none is supplied and the default is used), and new-style version specifiers can't be used since they are checked against the old JSON Schema.

Steps to reproduce:

```python
from xcube.core.store import new_data_store
cds = new_data_store('cds')
ds = cds.open_data(
    'satellite-soil-moisture:volumetric:monthly',
    time_range=['2015-01-01', '2015-12-31']
)
```

Result:

> Exception: the request you have submitted is not valid. Value 'v201912.0.0' not valid for parameter 'version', valid values are: v201706, v201812, v201912, v202012.

The variable names have changed too.

### PR DESCRIPTION
**Pull request by pont-us**
# Related issues

Closes #68 .

# Motivation

The parameter schemas for the CDS API backend (a.k.a. `cdsapi`) have slightly (and silently) changed -- for instance, the soil moisture product version number `v201912.0.0` now has to be given as `v201912`. These changes break many xcube-cds `open_data` calls. This PR updates the relevant backend calls and parameter schemas in `xcube-cds` to make them work with the current live API again.

# Description

## test/mock_results

These are just the updates of the canned API requests and responses used by the mock `cdsapi` client. They don't need much (or any?) reviewing.

## test/mocks.py

This file defines the mock `cdsapi` client. Significant changes, aimed at making it much easier to regenerate mock data from the live CDS API when the API changes. Previously this was a semi-manual process; now it just involves changing the `_BEHAVIOUR` variable and running pytest.

## test_era5.py, test_sea_ice_thickness.py, test_soil_moisture.py, test_store.py

Mainly just boilerplate changes to use the updated mock client code, which now supplies the client via a factory method.

## xcube_cds/datasets/*.{json,py}

These are the actual (fairly minor) changes in the backend calls to make them work with the current CDS API.

### CODE REVIEW

**Review by TonioF — COMMENTED** [review]
Three of the tests in ClientUrlTest fail when I change the _BEHAVIOUR enum from Mock to something else.
Two times it is a missing schema exception, the other time a TypeError ('tuple' object is not callable). Do you have the same behaviour?

**Comment by pont-us** [comment]
> Three of the tests in ClientUrlTest fail when I change the _BEHAVIOUR enum from Mock to something else. Two times it is a missing schema exception, the other time a TypeError ('tuple' object is not callable). Do you have the same behaviour?

Strange -- for me they all run. Which tests fail? And do you have credentials set in environment variables?

**Review by forman — APPROVED** [review]

**Comment by TonioF** [comment]
> > Three of the tests in ClientUrlTest fail when I change the _BEHAVIOUR enum from Mock to something else. Two times it is a missing schema exception, the other time a TypeError ('tuple' object is not callable). Do you have the same behaviour?
> 
> Strange -- for me they all run. Which tests fail? And do you have credentials set in environment variables?

In ClientUrlTest, it is test_client_url_and_key_environment_variables, test_client_url_and_key_parameters and test_client_url_and_key_rc_file . I set the behaviour to _Behaviour.SAVE_RESULTS. What is weird to me is that it is obvious they need to fail. They specify a wrong url and api key and then these are used to retrieve data from a client.

**Review by TonioF — APPROVED** [review]
Works!

**Pull request merged**
